# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)


In [38]:
import numpy as np
a= np.array([1,2,3])
b= np.array([4,5,6])
dot= np.dot(a,b)
print(dot)


32


In [39]:
id= np.identity(5, dtype=float)
print("identity matrix \n" ,id)

identity matrix 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
div= np.arange(10,51)
div_five= div[div % 5 == 0]
print(div_five)

[10 15 20 25 30 35 40 45 50]


In [41]:
c= np.array([[10 ,20 , 43],
             [2, 95,95],
             [25, 41, 9]])
max_1 =np.max(c ,axis=1)
print(max_1)

[43 95 41]


In [42]:
d= np.array([[90 ,20 , 43, 32],
             [2, 89 ,95, 56],
             [25, 41, 9, 11],
             [11, 34, 54 ,53]])
np.fill_diagonal(d,9)
print(d)

[[ 9 20 43 32]
 [ 2  9 95 56]
 [25 41  9 11]
 [11 34 54  9]]


In [45]:
arr1= np.random.randint(1, 100 , size=(10 ,10))
print("before\n" , arr1)
even_erased = np.where( arr1 % 2 == 0 ,0 , arr1)
print("after\n" , even_erased)

before
 [[42 80 45 53 96 39 95 39 28 84]
 [25 99 18 19 41 22 67 40 27 26]
 [49 84 19 77 37 61 27 32 30 72]
 [61 41 12 13 14 87 96 12 33 93]
 [77 57 85 64 64  3 80 19 13 27]
 [74 38 11 67 36 83 62 76 60 11]
 [79 75 49 25 64 11 39 59 20 41]
 [63 91  9  2  3 67 66 64 63 78]
 [39 71 16 36 78 38 48 41 83 37]
 [23 53 95 65 42 96 36 55 53 46]]
after
 [[ 0  0 45 53  0 39 95 39  0  0]
 [25 99  0 19 41  0 67  0 27  0]
 [49  0 19 77 37 61 27  0  0  0]
 [61 41  0 13  0 87  0  0 33 93]
 [77 57 85  0  0  3  0 19 13 27]
 [ 0  0 11 67  0 83  0  0  0 11]
 [79 75 49 25  0 11 39 59  0 41]
 [63 91  9  0  3 67  0  0 63  0]
 [39 71  0  0  0  0  0 41 83 37]
 [23 53 95 65  0  0  0 55 53  0]]


In [49]:
e= [1,2,3]
f=[1,2,3]
def compare_arr(arr1, arr2):
  return np.array_equal(arr1,arr2)
print(compare_arr(e,f))

True


In [51]:
flattened = c.flatten()
reshaped =flattened.reshape(c.shape)
print(flattened)
print(reshaped)

[10 20 43  2 95 95 25 41  9]
[[10 20 43]
 [ 2 95 95]
 [25 41  9]]


In [56]:
mean= np.mean(arr1)
mean= np.mean(arr1)
median =np.median(arr1)
std =np.std(arr1)
print(mean, "\n" , median, "\n" , std, "\n")

49.61 
 47.0 
 26.37722312905587 



In [58]:
zero_arr= np.zeros((6,6),dtype =int)
zero_arr[0,:]= 1
zero_arr[-1,:]= 1
zero_arr[:,0]= 1
zero_arr[:,-1]= 1
print(zero_arr)


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [22]:
import pandas as pd

data = {
    'name': ['dev','eva','thiya','kush', 'piyush'],
    'subject': ['Math', 'Science', 'eng', 'History', 'Science'],
    'score': [95, 17, 88, 45, 91]
}
df = pd.DataFrame(data)
print(df)
print("\nscore>80:")
print(df[df['score'] > 80])



     name  subject  score
0     dev     Math     95
1     eva  Science     17
2   thiya      eng     88
3    kush  History     45
4  piyush  Science     91

score>80:
     name  subject  score
0     dev     Math     95
2   thiya      eng     88
4  piyush  Science     91


In [25]:
import pandas as pd
data ={
    'math': [23 ,96 ,45 ,77 ,88 ,90],
    'science':[99 ,'NaN' ,75, 89 ,81, 79],
    'english':[65,78,43,84,69,92]
}
df=pd.DataFrame(data)
df['total']=df['math']+df['science']+df['english']
print(df)

   math  science  english  total
0    23       99       65    187
1    96       64       78    238
2    45       75       43    163
3    77       89       84    250
4    88       81       69    238
5    90       79       92    261


In [33]:
data={
    'department': ['it', 'finance','marketing','accounts','administration','hr','it','finance','hr','accounts'],
    'salary': [45000,67000,44560,78900,56743,11000,34567,12345,67900,9999]
}
df=pd.DataFrame(data)
avg_salary= df.groupby('department')['salary'].mean()
print(avg_salary)

department
accounts          44449.5
administration    56743.0
finance           39672.5
hr                39450.0
it                39783.5
marketing         44560.0
Name: salary, dtype: float64


In [62]:
""" from faker import Faker
fake = Faker()
def generate_fake_data(x):
      for i in range(0,x):
       print(fake.date())
      return
generate_fake_data(5) """
import numpy as np
import pandas as pd
date_strings = [
        '2025-05-23',
        '2023-01-15',
        '2024-07-10',
        '2022-12-05',
        '2025-03-01',
        '2021-06-20'
      ]
data= {
    'random_dates': date_strings
}
df=pd.DataFrame(data)
df.sort_values(by='random_dates',ascending=False)


random_dates
0   2025-05-23
4   2025-03-01
2   2024-07-10
1   2023-01-15
3   2022-12-05
5   2021-06-20

In [68]:
import pandas as pd
data ={
    'math': [23 ,96 ,45 ,77 ,88 ,90],
    'science':[99, np.nan, 75, 89 ,81, 79],
    'english':[65,78,43,84,69,92]
}
df=pd.DataFrame(data)
df.dropna(inplace=True)
print(df)

   math  science  english
0    23     99.0       65
2    45     75.0       43
3    77     89.0       84
4    88     81.0       69
5    90     79.0       92


In [73]:
import pandas as pd
from google.colab import files


uploaded = files.upload()


Saving Book1.csv to Book1 (3).csv


In [82]:
import pandas as pd
import io
import pandas as pd
import io

for filename in uploaded.keys():
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
top3= df.nlargest(3,'sales')
print(top3)

   sales
6  75643
5   3980
7    654


In [86]:
import numpy as np
import pandas as pd
date_strings = [
        '2025-05-23',
        '2023-01-15',
        '2024-07-10',
        '2022-12-05',
        '2025-03-01',
        '2021-06-20'
      ]
data= {
    'random_dates': date_strings
}
df=pd.DataFrame(data)
df['random_dates'] = pd.to_datetime(df['random_dates'])
df['month'] = df['random_dates'].dt.month
print(df)


  random_dates  month
0   2025-05-23      5
1   2023-01-15      1
2   2024-07-10      7
3   2022-12-05     12
4   2025-03-01      3
5   2021-06-20      6


In [94]:
import pandas as pd

data = {
    'name': ['dev','eva','thiya','kush', 'piyush','kush'],
    'email':['dev@emial.com','eva@email.com' ,'thiya@email.com','piyush2email.com','kush2email.com','eva@email.com']
}
df = pd.DataFrame(data)
unique= df.drop_duplicates(subset=['name','email'])
print(unique)


     name             email
0     dev     dev@emial.com
1     eva     eva@email.com
2   thiya   thiya@email.com
3    kush  piyush2email.com
4  piyush    kush2email.com
5    kush     eva@email.com


In [96]:
import pandas as pd
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000.0, 60000.5, 70000.2],
    'Department': ['HR', 'IT', 'Finance'],
    'Joined': [True, False, True]
}

df = pd.DataFrame(data)
print(df)
def get_numeric_df(df):
    return df.select_dtypes(include='number')
numeric_df = get_numeric_df(df)
print(numeric_df)


      name  Age   Salary Department  Joined
0    Alice   25  50000.0         HR    True
1      Bob   30  60000.5         IT   False
2  Charlie   35  70000.2    Finance    True
   Age   Salary
0   25  50000.0
1   30  60000.5
2   35  70000.2


In [98]:
import pandas as pd
data = {
    'feedback': [
        'the service was excellent!',
        'Not bad, could be better.',
        'excellent response time and support.',
        'totally average experience.',
        'EXCELLENT work by the team.',
        'Nothing special.'
    ]
}
df = pd.DataFrame(data)
print(df)
count = df['feedback'].str.contains(r'\bexcellent\b', case=False, na=False).sum()
print(f"\nNumber of rows containing the word 'excellent': {count}")


                               feedback
0            the service was excellent!
1             Not bad, could be better.
2  excellent response time and support.
3           totally average experience.
4           EXCELLENT work by the team.
5                      Nothing special.

Number of rows containing the word 'excellent': 3
