<a href="https://colab.research.google.com/github/NISHTHA0305/NISHTHA0305.github.io/blob/main/PS_practice_sheet_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.random.randint(1,10,size=(3,3,3))
print(arr1)
sum1=np.sum(arr1,axis=0)
print(sum1)
sum2=np.sum(arr1,axis=1)
print(sum2)
sum3=np.sum(arr1,axis=2)
print(sum3)


[[[4 4 2]
  [2 7 9]
  [5 3 2]]

 [[5 5 9]
  [2 3 5]
  [7 7 6]]

 [[4 3 4]
  [3 3 2]
  [2 8 6]]]
[[13 12 15]
 [ 7 13 16]
 [14 18 14]]
[[11 14 13]
 [14 15 20]
 [ 9 14 12]]
[[10 18 10]
 [19 10 20]
 [11  8 16]]


In [ ]:
import numpy as np
import random
arr3=np.random.randint(1,10,size=(5,5))
arr2=np.random.randint(1,20,size=(5,5))
print(arr1)
print(arr2)
new_arr=np.where(arr3<arr2, 0,arr3)
print(new_arr)


[[[4 4 2]
  [2 7 9]
  [5 3 2]]

 [[5 5 9]
  [2 3 5]
  [7 7 6]]

 [[4 3 4]
  [3 3 2]
  [2 8 6]]]
[[ 1  4 15 19 13]
 [18  2  1  4  4]
 [18  8 10 14 16]
 [ 3 11 17  6 10]
 [ 3  7  7 12 18]]
[[3 5 0 0 0]
 [0 6 8 5 0]
 [0 0 0 0 0]
 [6 0 0 7 0]
 [0 0 0 0 0]]


In [ ]:
import numpy as np
import pandas as pd
def moving_average(arr):
  kernel=np.ones(3)/3
  return np.convolve(arr,kernel,mode='valid')
moving_average([1,2,3,98,65,4,3])

array([ 2.        , 34.33333333, 55.33333333, 55.66666667, 24.        ])

In [ ]:
import numpy as np
from scipy.spatial import distance_matrix

def euclidean_distance(arr1,arr2):
  return distance_matrix(arr1,arr2)

euclidean_distance([[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]])


array([[10.39230485, 15.58845727],
       [ 5.19615242, 10.39230485]])

In [ ]:
import numpy as np
import random
arr1=np.random.randint(1,100, size=(3,3))
print(arr1)
max_in_row=np.max(arr1,axis=0)
max_in_col=np.max(arr1,axis=1)
print(max_in_row)
print(max_in_col)

[[16 76 18]
 [42 93 37]
 [96 32 29]]
[96 93 37]
[76 93 96]


In [ ]:
import numpy as np
import random
def mostFreqEle(arr1):
    flat_arr = arr1.flatten()
    unique_elements, counts = np.unique(flat_arr, return_counts=True)
    max_count_index = np.argmax(counts)
    return unique_elements[max_count_index]
if __name__ == "__main__":
  arr1= np.random.randint(1,1000,size=(100,10))
  print(arr1)
  print(mostFreqEle(arr1))

[[130 443 167 922 693 951 453 994 961 472]
 [760 913 194 435   8  45 469 906 382 473]
 [944 619 820 397 152  22 215   8 330 877]
 [339 907 980 232 772 790 448 348 509 190]
 [262 198 205 369 480 143 843  45 527 965]
 [991 982 266 773 743  40 600 762 880 832]
 [ 67 969 344 211 790  10 673  99 276 495]
 [660 287 823 801 574 901  79 322 163 530]
 [457 892 982 543 331 507  25 518 987 952]
 [537 653 600 550 356 973 685 164 645 235]
 [759 164   8 948 901 193 428 442  89 672]
 [405 138 107 578 381 516 762 111 183 976]
 [277 613  97 416 220 106 498 563 251 140]
 [630 139 237 926 735 492 323 510 101 251]
 [850  37 110 704 724  19 363 190 400 930]
 [687  19 391 224 759 234 941 432 897 875]
 [934 672  67 691 813 129 704 992  81 548]
 [587 719 667  85 772  16 162   8 150 978]
 [536 365 889 758 871  97 327 774 673 200]
 [406 688 906 965 807 497 247 185 755 929]
 [660 716 771 504 235 935 909 806 916 749]
 [546 918 882 590 982 618 345  21 888 307]
 [238 649 759 944 692 219 505 829 646  49]
 [775 630 2

In [ ]:
import numpy as np
def find_outliers(data):
  q1= np.percentile(data,25)
  q3= np.percentile(data,75)
  iqr=q3-q1
  lower_bound=q1-1.5*iqr
  upper_bound=q3+1.5*iqr
  outliers=data[(data<lower_bound)|(data>upper_bound)]
  return outliers

data=np.random.randint(1,1000,size=(4,5))
outlier=find_outliers(data)
print(data)
print(outlier)

[[333 107 144 238 401]
 [102 950 466 463 566]
 [916 532  22 254 986]
 [578 374 858 119 356]]
[]


In [ ]:
import numpy as np
def split_arr(arr,num_subarr):
  if len(arr)%num_subarr !=0:
    raise ValueError("Invalid number of subarrays")
  return np.split(arr,num_subarr)
arr=np.random.randint(1,100,size=(10))
print(arr)
print(split_arr(arr,2))


[62  2 92 72 13 40 75 44 41 61]
[array([62,  2, 92, 72, 13]), array([40, 75, 44, 41, 61])]


In [ ]:
import numpy as np
def matrix_multiply(a,b):
    if a.shape[1] != b.shape[0]:
        raise ValueError("not compatible")
    result = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j]+=a[i,k]*b[k,j]
    return result
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
C = matrix_multiply(a,b)
print(C)

[[19. 22.]
 [43. 50.]]


In [ ]:
import pandas as pd
df = pd.read_csv('employees.csv', parse_dates=['join_date'])
target_year = 202
df_year = df[df['join_date'].dt.year == target_year]
monthly_counts = df_year['join_date'].dt.month.value_counts().sort_index()
monthly_counts.index = monthly_counts.index.map(lambda x: pd.to_datetime(f'{x}', format='%m').strftime('%B'))
print(f"Employee join count per month for {target_year}:\n")
print(monthly_counts)


FileNotFoundError: [Errno 2] No such file or directory: 'employees.csv'

In [ ]:
import pandas as pd
data = {
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'duration': ['01:30:00', '00:45:15', '02:15:30', '00:10:00', '03:05:45']
}
df = pd.DataFrame(data)
df['total_seconds']=pd.to_timedelta(df['duration']).dt.total_seconds().astype(int)
print(df)


   employee_id     name  duration  total_seconds
0            1    Alice  01:30:00           5400
1            2      Bob  00:45:15           2715
2            3  Charlie  02:15:30           8130
3            4    David  00:10:00            600
4            5      Eva  03:05:45          11145


In [ ]:
import pandas as pd
left_data = {
    'employee_id': [1,2,3,4],
    'department': ['HR', 'HR','Finance','IT'],
    'name': ['Alice','Charlie','David','Eva']
}
left_df = pd.DataFrame(left_data)
right_data = {
    'employee_id': [1, 2, 4],
    'department': ['HR', 'IT', 'Finance'],
    'salary': [50000, 60000, 55000]
}
right_df =pd.DataFrame(right_data)
merged_df= pd.merge(left_df, right_df, on=['employee_id','department'],how='left',indicator=True)
missing_in_right=merged_df[merged_df['_merge']=='left_only']
print(missing_in_right)


   employee_id department     name  salary     _merge
1            2         HR  Charlie     NaN  left_only
2            3    Finance    David     NaN  left_only
3            4         IT      Eva     NaN  left_only


In [ ]:
import pandas as pd
import pandas as pd
data = {
    'user_id': [1,1,1,2,2,3,3,3,3],
    'purchase_value': [250, 400, 100, 300, 200,150, 450,150,300]
}
df = pd.DataFrame(data)
print(df)
df_sorted=df.sort_values(['user_id','purchase_value'],ascending=[True,False])
second_highest=df_sorted.groupby('user_id').nth(1).reset_index()
print(second_highest)

   user_id  purchase_value
0        1             250
1        1             400
2        1             100
3        2             300
4        2             200
5        3             150
6        3             450
7        3             150
8        3             300
   index  user_id  purchase_value
0      0        1             250
1      4        2             200
2      8        3             300


In [ ]:
import numpy as np
data = {
    'customer_id': ['A','A','A','B','B','C','C', 'C','C'],
    'order_timestamp':[
        '2024-05-01 08:00:00','2024-05-01 09:15:00','2024-05-01 11:45:00',
        '2024-05-01 10:00:00','2024-05-01 12:30:00',
        '2024-05-01 07:00:00','2024-05-01 07:45:00','2024-05-01 08:15:00','2024-05-01 09:00:00'
    ]
}
df=pd.DataFrame(data)
df['order_timestamp']=pd.to_datetime(df['order_timestamp'])
df_sorted=df.sort_values(['customer_id','order_timestamp'])
df_sorted['time_diff']=df_sorted.groupby('customer_id')['order_timestamp'].diff()
df_sorted['time_diff']=df_sorted['time_diff'].dt.total_seconds()/60
print(df_sorted)
avg_tg_per_customer=df_sorted.groupby('customer_id')['time_diff'].mean().reset_index()
avg_tg_per_customer.rename(columns={'time_diff':'avg_time_gap_minutes'},inplace=True)
print(avg_tg_per_customer)


  customer_id     order_timestamp  time_diff
0           A 2024-05-01 08:00:00        NaN
1           A 2024-05-01 09:15:00       75.0
2           A 2024-05-01 11:45:00      150.0
3           B 2024-05-01 10:00:00        NaN
4           B 2024-05-01 12:30:00      150.0
5           C 2024-05-01 07:00:00        NaN
6           C 2024-05-01 07:45:00       45.0
7           C 2024-05-01 08:15:00       30.0
8           C 2024-05-01 09:00:00       45.0
  customer_id  avg_time_gap_minutes
0           A                 112.5
1           B                 150.0
2           C                  40.0


In [ ]:
import pandas as pd
import numpy as np
date_rng=pd.date_range(start='2024-01-01',end='2024-01-20',freq='D')
df = pd.DataFrame(date_rng, columns=['date'])
df['value']=np.random.randint(10,100,size=(len(date_rng)))
df.set_index('date',inplace=True)
df=df[df.index.dayofweek < 5]
df['5_day_rolling_avg']=df['value'].rolling(window=5).mean()
print(df)


            value  5_day_rolling_avg
date                                
2024-01-01     80                NaN
2024-01-02     60                NaN
2024-01-03     65                NaN
2024-01-04     38                NaN
2024-01-05     69               62.4
2024-01-08     17               49.8
2024-01-09     48               47.4
2024-01-10     11               36.6
2024-01-11     33               35.6
2024-01-12     38               29.4
2024-01-15     14               28.8
2024-01-16     16               22.4
2024-01-17     99               40.0
2024-01-18     72               47.8
2024-01-19     23               44.8


In [ ]:
import pandas as pd
data = {
    'date': ['2025-01-01','2025-01-02','2025-01-03','2025-01-04'],
    'open': [100,120,150,130],
    'close': [95,105,130,115]
}
df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)
df['pct_change']=((df['close']-df['open'])/df['open'])*100
df['drop_>10%']=df['pct_change']<-10
print(df)


            open  close  pct_change  drop_>10%
date                                          
2025-01-01   100     95   -5.000000      False
2025-01-02   120    105  -12.500000       True
2025-01-03   150    130  -13.333333       True
2025-01-04   130    115  -11.538462       True


In [ ]:
import pandas as pd
import re
data = {
    'text': [
        "#sunshine and #blueSkies today!",
        "no hashtags",
        "#python is great#coding #AI",
        "another day,another#coffee"
    ]
}
df=pd.DataFrame(data)
df['hashtags']=df['text'].apply(lambda x:re.findall(r'#\w+',x))
print(df)


                              text                 hashtags
0  #sunshine and #blueSkies today!  [#sunshine, #blueSkies]
1                      no hashtags                       []
2      #python is great#coding #AI  [#python, #coding, #AI]
3       another day,another#coffee                [#coffee]
